---
 - name: Environemnt Variables PATH
   command: echo "$PATH"
   register: path
 - debug: msg="{{ path.stdout }}"
 - debug: msg="{{ path.stderr }}"
 
 - name: Environemnt Variables GOPATH
   command: echo "$GOPATH"
   register: gopath
 - debug: msg="{{ gopath.stdout }}"
 - debug: msg="{{ gopath.stderr }}"
 
 - name: Environemnt Variables GOROOT
   command: echo "$GOROOT"
   register: goroot
 - debug: msg="{{ goroot.stdout }}"
 - debug: msg="{{ goroot.stderr }}"
 
 - name: install pre requist
   apt:
     name: "{{ item }}"
     state: present
     update_cache: yes
   with_items:  
      #- gtar
      - gzip
      - unzip
      - curl 
      - git 
      - wget
      - build-essential
      
 - name: mkdir /opt/go 
   file:
    path: /opt/go
    state: directory
    mode: 0755
    
 - name: Remove old installation of Go
   file:
     path: /usr/local/go
     state: absent
     
 - name: Install go    
   unarchive:
     src: https://storage.googleapis.com/golang/go1.8.1.linux-amd64.tar.gz
     dest: /usr/local
     remote_src: yes
     

...